# LambdaControls configuration.
# The controls mode. Available modes: default, controller, touchscreen
controls = "default"
# Auto switch mode.
auto_switch_mode = false

# Controller settings
[controller]
	# Controller's dead zone.
	dead_zone = 0.2
	# Inverts the right X axis.
	invert_right_x_axis = false
	unfocused_input = false
	# Controller to use.
	id = 0
	# Controller's type.
	type = "default"
	# Mouse speed in GUI.
	mouse_speed = 15.0
	# Rotation speed for look directions.
	rotation_speed = 40.0
	# Inverts the right Y axis.
	invert_right_y_axis = false

	# Controller controls.
	[controller.controls]
		# Drop item control.
		drop_item = "1"
		# Toggle smooth camera control.
		toggle_smooth_camera = "-1"
		# Swap hands control.
		swap_hands = "2"
		# Forward control.
		forward = "101"
		# Use control.
		use = "104"
		# Sprint control.
		sprint = "9"
		# Back control.
		back = "201"
		# Take screenshot control.
		screenshot = "13"
		# Inventory control.
		inventory = "3"
		# Show player list control.
		player_list = "6"
		# Pause game control.
		pause_game = "7"
		# Attack control.
		attack = "105"
		# Open chat control.
		chat = "12"
		# Pick block control.
		pick_block = "14"
		# Sneak control.
		sneak = "10"
		# Toggle perspective control.
		toggle_perspective = "11"
		# Jump control.
		jump = "0"

[hud]
	# Dertermines where the movements buttons are.
	side = "left"
	# Enables the HUD.
	enable = true

[gameplay]

	[gameplay.fly]
		vertical_drifting = true
		drifting = true

